name: emustack
channels:
  - conda-forge
dependencies:
  - python>3.8
  - pip
  - numpy
  - suitesparse
  - metis
  - compilers
  - openblas # is this needed?
  - scipy
  - matplotlib
  - gmsh
  - make
  - cmake
  - pkg-config
  - ninja
