name: Test
run-name: ${{ github.repository }} testing
on: [push]
jobs:
  install-and-test:
    name: system (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-24.04] #, windows-latest
    runs-on: ${{ matrix.os }}
    env:
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install system packages
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends  \
          gfortran gcc make cmake \
          libsuitesparse-dev liblapack-dev libopenblas-dev
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and run tests
        run: |
          pip install .[test] -v
          pytest

  install-and-test-conda:
    name: conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    env:
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Install package and run tests
        run: |
          micromamba install python=${{ matrix.python-version }}
          pip install .[test] -v
          pytest